services:
  - type: web
    name: smart-sorter-v5
    env: docker
    plan: starter

    dockerfilePath: ./Dockerfile

    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-2.0-flash

    autoDeploy: true
