services:
  - type: web
    name: smart-sorter-v5
    env: docker
    plan: starter

    dockerfilePath: ./Dockerfile

    autoDeploy: true

    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-2.0-flash

    buildCommand: pip install -r requirements.txt
    startCommand: python smart_sorter_web.py

    autoDeploy: true

